FROM node:lts AS dependencies

# Variables necesarias para el build (incluyendo Supabase)
ARG NEXT_PUBLIC_API_URL_CLIENT
ARG NODE_ENV
ARG NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_UMAMI_WEBSITE_ID

# Variables de entorno para el build
ENV NEXT_PUBLIC_API_URL_CLIENT=${NEXT_PUBLIC_API_URL_CLIENT}
ENV NODE_ENV=${NODE_ENV}
ENV NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET=${NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET}
ENV NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
ENV NEXT_PUBLIC_UMAMI_WEBSITE_ID=${NEXT_PUBLIC_UMAMI_WEBSITE_ID}

WORKDIR /frontend-tulk

COPY package.json ./
COPY pnpm-lock.yaml ./
COPY postcss.config.mjs ./
COPY eslint.config.mjs ./
COPY tsconfig.json ./
COPY prisma/schema.prisma .

RUN npm install -g pnpm
RUN pnpm install

COPY . .

RUN pnpm run prisma-create

RUN pnpm run build

EXPOSE 3000

CMD ["pnpm", "start"]
